export * from './lib/ngtsc/symbol';
export * from './lib/ngtsc/component.symbol';
export * from './lib/ngtsc/directive.symbol';
export * from './lib/ngtsc/injectable.symbol';
export * from './lib/ngtsc/module.symbol';
export * from './lib/ngtsc/pipe.symbol';
export * from './lib/ngtsc/workspace.symbols';
export * from './lib/ngtsc/trait-compiler';
export * from './lib/ngtsc/find-symbol';
export * from './lib/ngtsc/utils';
export { TemplateNode } from './lib/ngtsc/template-transform.visitor';
